package com.attendify.attendify_api.user.entity.enums;

public enum Permission {
    USER_FORCE_READ,
    USER_READ_ALL,
    USER_READ_DELETED,
    USER_READ_WITH_DELETED,
    USER_FORCE_CREATE,
    USER_FORCE_DELETE,
    USER_RESTORE,

    CATEGORY_READ_DELETED,
    CATEGORY_READ_WITH_DELETED,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_FORCE_UPDATE,
    CATEGORY_DELETE,
    CATEGORY_FORCE_DELETE,
    CATEGORY_RESTORE,

    EVENT_READ_DELETED,
    EVENT_READ_WITH_DELETED,
    EVENT_CREATE,
    EVENT_UPDATE,
    EVENT_FORCE_UPDATE,
    EVENT_DELETE,
    EVENT_FORCE_DELETE,
    EVENT_RESTORE,

    EVENT_REGISTRATION_READ_BY_EVENT,
    EVENT_REGISTRATION_READ_DELETED,
    EVENT_REGISTRATION_READ_WITH_DELETED,
    EVENT_REGISTRATION_CREATE,
    EVENT_REGISTRATION_CHECKIN,
    EVENT_REGISTRATION_FORCE_CHECKIN,
    EVENT_REGISTRATION_DELETE,
    EVENT_REGISTRATION_FORCE_DELETE,
    EVENT_REGISTRATION_RESTORE
}
