package com.attendify.attendify_api.user.model;

public enum Permission {
    USER_READ,
    USER_READ_DELETED,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_RESTORE,

    CATEGORY_READ,
    CATEGORY_READ_DELETED,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,
    CATEGORY_RESTORE,

    EVENT_READ,
    EVENT_READ_DELETED,
    EVENT_CREATE,
    EVENT_UPDATE,
    EVENT_DELETE,
    EVENT_RESTORE,

    EVENT_REGISTRATION_READ,
    EVENT_REGISTRATION_READ_ADMIN,
    EVENT_REGISTRATION_READ_DELETED,
    EVENT_REGISTRATION_CREATE,
    EVENT_REGISTRATION_UPDATE,
    EVENT_REGISTRATION_DELETE,
    EVENT_REGISTRATION_RESTORE
}
