package com.attendify.attendify_api.user.model.enums;

public enum Permission {
    USER_READ,
    USER_PASSWORD,
    USER_EMAIL,
    USER_DELETE,

    CATEGORY_READ,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    EVENT_READ,
    EVENT_CREATE,
    EVENT_UPDATE,
    EVENT_DELETE,

    EVENT_REGISTRATION_READ,
    EVENT_REGISTRATION_CREATE,
    EVENT_REGISTRATION_UPDATE,
    EVENT_REGISTRATION_DELETE
}
